energize_andover/urls.py
from django.conf.urls import url
from . import views
from ea_parser import views as ParseViews
from school_adder import views as AdderViews
from login import views as LoginViews
from user_management import views as UMViews
from school_editing import views as SEViews
from table_sorter import views as TableViews
from qr_codes import views as QRViews
from qr_generator import views as QRGeneratorViews
from bacnet import views as BViews

app_name = 'gismap'
urlpatterns = [
    url(r'^$', ParseViews.index, name='index'),
    url(r'^electric', views.electrical_mapping, name='electric'),
    url(r'^School(?P<school_id>[0-9]+)', views.school, name='school'),
    url(r'^Room(?P<room_id>[0-9]+)', views.room, name='room'),
    url(r'^Circuit(?P<circuit_id>[0-9]+)', views.circuit, name='circuit'),
    url(r'^Panel(?P<panel_id>[0-9]+)', views.panel, name='panel'),
    url(r'^Closet(?P<closet_id>[0-9]+)', views.closet, name='closet'),
    url(r'^Edit/Panel(?P<panel_id>[0-9]+)', SEViews.panel_editing, name='panel_editing'),
    url(r'^Edit/Room(?P<room_id>[0-9]+)', SEViews.room_editing, name='room_editing'),
    url(r'^Edit/Device(?P<device_id>[0-9]+)', SEViews.device_editing, name='device_editing'),
    url(r'^Edit/Circuit(?P<circuit_id>[0-9]+)', SEViews.circuit_editing, name='circuit_editing'),
    url(r'^Edit/Closet(?P<closet_id>[0-9]+)', SEViews.closet_editing, name='closet_editing'),
    url(r'^MapAdder', AdderViews.adder, name='adder'),
    url(r'^Populate', AdderViews.populate, name='populator'),
    url(r'^Search', views.search, name='search'),
    url(r'^Dictionary', views.dictionary, name = 'dictionary'),
    url(r'^ChangeLog', views.changelog, name = 'changelog'),
    url(r'^Device(?P<device_id>[0-9]+)', views.device, name = "device"),
    url(r'^Login', LoginViews.login, name = "login"),
    url(r'^UserCreation', UMViews.user_creation, name = "usercreation"),
    url(r'^Management', UMViews.user_management, name = "user_management"),
    url(r'^Editing(?P<user_id>[0-9]+)', UMViews.user_editing, name = "user_editing"),
    url(r'^TableSorting(?P<school_id>[0-9]+)(?P<type>[-\w]+)', TableViews.list, name='table_sorting'),
    url(r'^QRCode/School(?P<school_id>[0-9]+)/Room(?P<qr_id>[0-9]+)', QRViews.qr_rooms_redirect, name='qr_room_redirect'),
    url(r'^QRCode/School(?P<school_id>[0-9]+)/Panel(?P<qr_id>[0-9]+)', QRViews.qr_panels_redirect, name='qr_panel_redirect'),
    url(r'^QRCode/School(?P<school_id>[0-9]+)/Closet(?P<qr_id>[0-9]+)', QRViews.qr_closets_redirect, name='qr_closet_redirect'),
    url(r'^QRGenerator/room_codes.pdf', QRGeneratorViews.open_rooms, name='room_codes'),
    url(r'^QRGenerator/panel_codes.pdf', QRGeneratorViews.open_panels, name='panel_codes'),
    url(r'^QRGenerator/closet_codes.pdf', QRGeneratorViews.open_closets, name='closet_codes'),
    url(r'^QRGenerator', QRGeneratorViews.generator, name='qr_generator'),
    url(r'^SVG(?P<school_id>[0-9]+)', views.topology, name='SVG'),
    url(r'^Graph(?P<school_id>[0-9]+)', BViews.return_data, name='graph')
]

mysite/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

# from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings
from mezzanine.pages.views import page


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    # url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # energize_andover url
    #url(r'^energize_andover/', include('energize_andover.energize_andover.urls')),
    #url(r'^', include('energize_andover.energize_andover.urls')),
    url(r'^energize_andover/', include('energize_andover.urls', namespace="energize_andover")),
    url(r'^', include('energize_andover.urls')),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    # NOTE: Don't forget to import the view function too!

    url("^", page, {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.blog.views.blog_post_list, name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    url("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

theme/models.py
from django.db import models

# Create your models here.

theme/templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}
{% load pages_tags mezzanine_tags i18n staticfiles %}
{% load static %}
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <title>{% block meta_title %}{% endblock %}</title>
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
  {% ifinstalled mezzanine.blog %}
  <link rel="alternate" type="application/rss+xml" title="RSS" href="{% url 'blog_post_feed' 'rss' %}">
  <link rel="alternate" type="application/atom+xml" title="Atom" href="{% url 'blog_post_feed' 'atom' %}">
  {% endifinstalled %}

  {% compress css %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css">
  <!--
  {% if LANGUAGE_BIDI %}
  <link rel="stylesheet" href="{% static 'css/bootstrap-rtl.css' %}">
  {% endif %}
  {% ifinstalled cartridge.shop %}
  <link rel="stylesheet" href="{% static 'css/cartridge.css' %}">
  {% if LANGUAGE_BIDI %}
  <link rel="stylesheet" href="{% static 'css/cartridge.rtl.css' %}">

  {% endif %}

  {% endifinstalled %}
  -->
  {% block extra_css %}{% endblock %}

  {% endcompress %}

  {% compress js %}
  <script type="text/javascript" src="{% static 'jquery/jquery-3.2.1.js' %}"></script>
  <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
  <script type="text/javascript" src="{% static 'js/Chart.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap-extras.js' %}"></script>
  <script src="{% static 'addons/pager/jquery.tablesorter.pager.js' %}"></script>

  <link href="{% static 'dist/css/theme.default.min.css' %}" rel="stylesheet">
  <script src="{% static 'dist/js/jquery.tablesorter.min.js' %}"></script>
  <script src="{% static 'dist/js/jquery.tablesorter.widgets.min.js' %}"></script>


  {% block extra_js %}{% endblock %}
  {% endcompress %}

  {% block extra_head %}{% endblock %}
</head>

<body id="{% block body_id %}body{% endblock %}">

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'energize_andover:electric' %}">Electrical Mapping</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
            <li>
                <a href="{% url 'energize_andover:qr_generator' %}">QR Generator</a>
            </li>
            <li>
                <a href="http://www.energizeandover.com/" target="_blank">Energize Andover</a>
            </li>
            <li>
                <a href="http://projectgle.weebly.com/" target="_blank">Project GLE</a>
            </li>
      </ul>
    </div>
  </div>
</nav>

  <div class="container">
    <div class="row">

      <div class="col-md-12 middle">
        {% block main %}{% endblock %}
      </div>

    </div>
  </div>
</body>
</html>