energize_andover/urls.py
from django.conf.urls import url
from . import views
from ea_parser import views as ParseViews
from school_adder import views as AdderViews
from login import views as LoginViews
from user_management import views as UMViews
from school_editing import views as SEViews
from table_sorter import views as TableViews
from qr_codes import views as QRViews
from qr_generator import views as QRGeneratorViews
from bacnet import views as BViews

app_name = 'gismap'
urlpatterns = [
    url(r'^$', ParseViews.index, name='index'),
    url(r'^electric', views.electrical_mapping, name='electric'),
    url(r'^School(?P<school_id>[0-9]+)', views.school, name='school'),
    url(r'^Room(?P<room_id>[0-9]+)', views.room, name='room'),
    url(r'^Circuit(?P<circuit_id>[0-9]+)', views.circuit, name='circuit'),
    url(r'^Panel(?P<panel_id>[0-9]+)', views.panel, name='panel'),
    url(r'^Closet(?P<closet_id>[0-9]+)', views.closet, name='closet'),
    url(r'^Edit/Panel(?P<panel_id>[0-9]+)', SEViews.panel_editing, name='panel_editing'),
    url(r'^Edit/Room(?P<room_id>[0-9]+)', SEViews.room_editing, name='room_editing'),
    url(r'^Edit/Device(?P<device_id>[0-9]+)', SEViews.device_editing, name='device_editing'),
    url(r'^Edit/Circuit(?P<circuit_id>[0-9]+)', SEViews.circuit_editing, name='circuit_editing'),
    url(r'^Edit/Closet(?P<closet_id>[0-9]+)', SEViews.closet_editing, name='closet_editing'),
    url(r'^MapAdder', AdderViews.adder, name='adder'),
    url(r'^Populate', AdderViews.populate, name='populator'),
    url(r'^Search', views.search, name='search'),
    url(r'^Dictionary', views.dictionary, name = 'dictionary'),
    url(r'^ChangeLog', views.changelog, name = 'changelog'),
    url(r'^Device(?P<device_id>[0-9]+)', views.device, name = "device"),
    url(r'^Login', LoginViews.login, name = "login"),
    url(r'^UserCreation', UMViews.user_creation, name = "usercreation"),
    url(r'^Management', UMViews.user_management, name = "user_management"),
    url(r'^Editing(?P<user_id>[0-9]+)', UMViews.user_editing, name = "user_editing"),
    url(r'^TableSorting(?P<school_id>[0-9]+)(?P<type>[-\w]+)', TableViews.list, name='table_sorting'),
    url(r'^QRCode/School(?P<school_id>[0-9]+)/Room(?P<qr_id>[0-9]+)', QRViews.qr_rooms_redirect, name='qr_room_redirect'),
    url(r'^QRCode/School(?P<school_id>[0-9]+)/Panel(?P<qr_id>[0-9]+)', QRViews.qr_panels_redirect, name='qr_panel_redirect'),
    url(r'^QRCode/School(?P<school_id>[0-9]+)/Closet(?P<qr_id>[0-9]+)', QRViews.qr_closets_redirect, name='qr_closet_redirect'),
    url(r'^QRGenerator/room_codes.pdf', QRGeneratorViews.open_rooms, name='room_codes'),
    url(r'^QRGenerator/panel_codes.pdf', QRGeneratorViews.open_panels, name='panel_codes'),
    url(r'^QRGenerator/closet_codes.pdf', QRGeneratorViews.open_closets, name='closet_codes'),
    url(r'^QRGenerator', QRGeneratorViews.generator, name='qr_generator'),
    url(r'^SVG(?P<school_id>[0-9]+)', views.topology, name='SVG'),
    url(r'^Graph(?P<school_id>[0-9]+)', BViews.return_data, name='graph')
]

mysite/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

# from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings
from mezzanine.pages.views import page


admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    # url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # energize_andover url
    #url(r'^energize_andover/', include('energize_andover.energize_andover.urls')),
    #url(r'^', include('energize_andover.energize_andover.urls')),
    url(r'^energize_andover/', include('energize_andover.urls', namespace="energize_andover")),
    url(r'^', include('energize_andover.urls')),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    # NOTE: Don't forget to import the view function too!

    url("^", page, {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.blog.views.blog_post_list, name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    url("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

energize_andover/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class School(models.Model):
    Name = models.CharField(max_length=30)
    # Notes = models.CharField(max_length=1000, default='')

    def panels(self):
        return Panel.objects.filter(School__pk=self.pk)

    def rooms(self):
        return Room.objects.filter(School__pk=self.pk)

    def closets(self):
        return Closet.objects.filter(School__pk=self.pk)

    def devices(self):
        return Device.objects.filter(School__pk=self.pk)
        """
        panels = self.panels()
        devs = []
        for i in panels:
            for j in i.circuits():
                for k in j.devices():
                    if k not in devs:
                        devs.append(k)
        return devs
        """

    def __str__(self):
        return self.Name


class Closet(models.Model):
    Name = models.CharField(max_length=30)
    Old_Name = models.CharField(max_length=20, default='')
    School = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    Notes = models.CharField(max_length=1000, default='')
    QID = models.IntegerField(default=0)

    def __str__(self):
        return self.Old_Name

    def to_string(self):
        return self.Old_Name + " / " + self.Name


class Panel(models.Model):
    Name = models.CharField(max_length=30)
    Voltage = models.CharField(max_length=20, default='0')
    Location = models.CharField(max_length=30, default='')
    FQN = models.CharField(max_length=50, default="MWSB")
    QID = models.IntegerField(default=0)
    Panels = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    School = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    Closet = models.ForeignKey(
        Closet,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    Notes = models.CharField(max_length=1000, default='')

    def rooms(self):
        return Room.objects.filter(Panels__pk=self.pk)

    def circuits(self):
        return Circuit.objects.filter(Panel=self.pk)

    def panels(self):
        return Panel.objects.filter(Panels__pk=self.pk)

    def fqn(self):
        return self.FQN

    def __str__(self):
        return self.Name

    def to_string(self):
        try:
            return self.FQN + " (" + self.Name + "), Rm. " + self.Closet.Name
        except:
            return self.FQN + " (" + self.Name + ")"


class Room(models.Model):
    Name = models.CharField(max_length=30)
    OldName = models.CharField(max_length=30, default='')
    Type = models.CharField(max_length=30, default='')
    School = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    Panels = models.ManyToManyField(Panel,
                                    blank=True,)
    Notes = models.CharField(max_length=1000, default = '')
    QID = models.IntegerField(default=0)

    def panels(self):
        return self.Panels.all()

    def school(self):
        return self.School

    def circuits(self):
        return Circuit.objects.filter(Rooms__pk=self.pk)

    def __str__(self):
        return self.OldName

    def to_string(self):
        return self.Name + " / " + self.OldName + " / " + self.Type


class Circuit(models.Model):
    Name = models.CharField(max_length=100)
    Number = models.CharField(default = "0", max_length = 10)
    FQN = models.CharField(max_length=50, default="MWSB")
    Function = models.CharField(default = "NA", max_length = 50)
    Panel = models.ForeignKey(
        Panel,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    School = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    Rooms = models.ManyToManyField(Room,
                        blank=True)
    Notes = models.CharField(max_length=1000, default = '')

    def rooms(self):
        return self.Rooms.all()

    def devices(self):
        return Device.objects.filter(Circuit__pk=self.pk)

    def school (self):
        return self.Panel.School

    def __str__(self):
        out = str(self.Panel) + ', circuit ' + str(self.Number) + ': '
        #rooms = self.Rooms.all()
        #for room in rooms:
        #    out += room.__str__()
        return out

    def to_string(self):
        to_str = self.FQN + " | " + self.Name
        if not len(self.devices()) == 0:
            dev = " | 1) " + self.devices()[0].to_string()
            rm = self.devices()[0].Room
            for i in range(1, len(self.devices())):
                dev += ("; " + str(i+1) + ") " + self.devices()[i].to_string())
            to_str += (dev)
        return to_str


class Device(models.Model):
    Name = models.CharField(max_length=50)
    Circuit = models.ManyToManyField(
        Circuit,
        blank=True,
    )
    School = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    Associated_Devices = models.ManyToManyField(
        'self',
        blank=True,
    )
    Power = models.CharField(max_length=10)
    Location = models.CharField(max_length=30)
    Room = models.ForeignKey(
        Room,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    Number = models.IntegerField(default = 0)
    Notes = models.CharField(max_length=1000, default = '')

    def circuits(self):
        return self.Circuit.all()

    def rooms(self):
        return self.Room

    def __str__(self):
        str = self.Name
        if self.Room is not None:
            str+=(", Rm:" + self.Room.Name)
        return str

    def to_string(self):
        to_str = self.Name
        if self.Room is not None:
            to_str += (", Rm: " + self.Room.Name)
        return to_str


class Transformer(models.Model):
    Name = models.CharField(max_length=50, default = '')
    Notes = models.CharField(max_length=1000, default = '')
    FQN = models.CharField(max_length=50, default = '')
    School = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )

    def __str__(self):
        return self.Name


class SpecialUser(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE)
    Authorized_Schools = models.ManyToManyField(School, blank=True)
    Notes = models.CharField(max_length=1000, default='')

login/models.py
from django.db import models

# Create your models here.

qr_generator/models.py
from django.db import models

# Create your models here.

user_management/models.py
from django.db import models

# Create your models here.

energize_andover/forms.py
from django import forms
from .models import *
import pandas as pd



class NewSchoolForm(forms.Form):
    Name = forms.CharField(required=True)



class SearchForm(forms.Form):
    entry = forms.CharField(
        label = 'Search:',
        required = False
    )
    school = forms.CharField(
        required = False
    )
    rooms = forms.BooleanField(
        label = 'Rooms',
        required = False
    )
    panels = forms.BooleanField(
        label = 'Panels',
        required = False
    )
    circuits = forms.BooleanField(
        label = 'Devices',
        required = False
    )
    closets = forms.BooleanField(
        label = 'Closets',
        required = False
    )

login/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(
        label = 'Username: ',
        required = True
    )
    password = forms.CharField(
        widget=forms.PasswordInput,
        label = "Password: ",
        required=True
    )

qr_generator/views.py
import os

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from login.views import check_status, School
from qr_generator.script import QRGenerator

def generator(request):
    if check_status(request) is False:
        return HttpResponseRedirect("Login")
    schools = School.objects.filter()
    for school in School.objects.all():
        if request.POST.get(str(school.id)):
            return render(request, 'energize_andover/QRGenerator.html',
                  {'school': school.id, 'selected': True})
    if request.POST.get("Generate"):
        QRGenerator.generate(school.id, rooms=request.POST.get("Rooms"), panels=request.POST.get("Panels"), closets=request.POST.get("Closets"))
        os.chdir('/var/www/gismap/qr_generator')
        room = False
        panel = False
        closet = False
        if os.path.exists('room_codes.pdf'):
            room = True
        if os.path.exists('panel_codes.pdf'):
            panel = True
        if os.path.exists('closet_codes.pdf'):
            closet = True
        os.chdir('..')
        return render(request, 'energize_andover/QRGenerator.html', {'generate': True, 'rooms': room, 'panels': panel, 'closets': closet})
    return render(request, 'energize_andover/QRGenerator.html', {'schools': schools})

def open_rooms(request):
    os.chdir('/var/www/gismap/qr_generator')
    with open('room_codes.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'filename=room_codes.pdf'
        os.chdir('..')
        return response

def open_panels(request):
    os.chdir('/var/www/gismap/qr_generator')
    with open('panel_codes.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'filename=panel_codes.pdf'
        os.chdir('..')
        return response

def open_closets(request):
    os.chdir('/var/www/gismap/qr_generator')
    with open('closet_codes.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'filename=closet_codes.pdf'
        os.chdir('..')
        return response

energize_andover/templates/energize_andover/Circuit.html
{% extends "pages/richtextpage.html" %}

{% block main %}
{% if form %}
<h1>Editing: {{circuit.Name}}</h1>
<!--
<form action=""  method="POST" enctype="multipart/form-data" name="Name">
    {% csrf_token %}
    <p>Name:</p>
    <p><input type="text" value = "{{circuit.Name}}" name = "Name"></p>
    <p><input type="submit" class="btn-xs" value="Save Name" name="Save Name" /></p>
</form>
-->
<form action=""  method="POST" enctype="multipart/form-data" name="Number">
    {% csrf_token %}
    <p>Number:</p>
    <p><input type="text" value = "{{circuit.Number}}" name = "Number"></p>
    <p><input type="submit" class="btn-xs" value="Save Number" name="Save Number" /></p>
</form>
<form action=""  method="POST" enctype="multipart/form-data" name="Notes">
    {% csrf_token %}
    <p>Notes:</p>
    <p><input type="text" value = "{{circuit.Notes}}" name = "Notes"></p>
    <p><input type="submit" class="btn-xs" value="Save Notes" name="Save Notes" /></p>
</form>
<form action=""  method="POST" enctype="multipart/form-data" name="Devices">
    {% csrf_token %}
    <p>Devices:</p>
    {% for dev in devices %}
    <p>{{dev.Name}}<input type="submit" class="btn-xs" value="Delete" name={{dev.id}} /></p>
    {% endfor %}
    <p><input type="text" value = "{{query}}" name = "Device_Query" size = "24">    {{device.Associated_Device}}</p>
    <p><input type="submit" class="btn-xs" value="Search" name="Search" /></p>
    <select id="id_Device" name = "Device">
    {% for dev in search_devices %}
        <option value="{{dev.id}}">{{dev.to_string}}</option>
    {% endfor %}
    </select>
    {% if not search_devices|length == 0 %}
        <p><input type="submit" class="btn-xs" value="Add Device" name="Add Device" /></p>
    {% endif %}
</form>
<button class="btn-xs" id="delete_object">Delete</button>
<div id="myModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <form action=""  method="POST" enctype="multipart/form-data" name="Confirm">
    {% csrf_token %}
    <p>Are you sure you want to delete?
    <p>Enter Username and Password to confirm:</p>
    <p>Username: <input type="text" value = "Username" name = "Username"></p>
    <p>Password: <input type="password" value = "Password" name = "Password"></p>
    <p><input type="submit" class="btn-xs" value="Confirm" name="Confirm" /></p>
</form>
  </div>
</div>

<script>
var modal = document.getElementById('myModal');
var btn = document.getElementById("delete_object");
var span = document.getElementsByClassName("close")[0];
btn.onclick = function() {
    modal.style.display = "block";
}
span.onclick = function() {
    modal.style.display = "none";
}
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

<li><a href="{% url 'energize_andover:circuit' circuit.id %}">Return to Circuit</a></li>
{% else %}
<h1> Circuit: {{circuit.FQN}} ({{circuit.Name}})</h1>
<p>School: <a href= "{% url 'energize_andover:school' school.id %}" >{{school.Name}}</a></p>

<p>Name: {{circuit.Name}}</p>
<p>Number: {{circuit.Number}}</p>
<p>FQN: {{circuit.FQN}}</p>
<p>Panel: <a href= "{% url 'energize_andover:panel' circuit.Panel.id %}" >{{circuit.Panel.FQN}} ({{circuit.Panel.Name}})</a></p>
{% if not devices.count == 0 %}
<p>Devices:</p>
{% for device in devices %}
    <li><a href = "{% url 'energize_andover:device' device.id %}">{{device.to_string}}</a></li>
{% endfor %}
{% else %}
    <p>Device: Spare</p>
{% endif %}
{% if not Rooms.count == 0 %}
<form>
<p>Rooms:</p>
{% for room in Rooms %}
    <li><a href="{% url 'energize_andover:room' room.id %}">{{room.to_string}}</a></li>
{% endfor %}

</form>
{% else %}
<p>Room: No Room data </p>
{% endif %}
{% if not circuit.Notes == '' %}
<p>Notes: {{circuit.Notes}}</p>
{% else %}
<p>Notes: No Notes </p>
{% endif %}
<form action="{% url 'energize_andover:circuit_editing' circuit.id %}"  method="POST" enctype="multipart/form-data" name="Edit">
    {% csrf_token %}
    <p><input type="submit" class="btn-xs" value="Edit" name="Edit" /></p>
</form>
{% endif %}
{% endblock %}

energize_andover/templates/energize_andover/Room.html
{% extends "pages/richtextpage.html" %}

{% block main %}
{% if form %}
<h1>Editing: {{room.Name}} </h1>
<form action=""  method="POST" enctype="multipart/form-data" name="Name">
    {% csrf_token %}
    <p>Name:</p>
    <p><input type="text" value = "{{room.Name}}" name = "Name"></p>
    <p><input type="submit" class="btn-xs" value="Save Name" name="Save Name" /></p>
</form>
<form action=""  method="POST" enctype="multipart/form-data" name="Old Name">
    {% csrf_token %}
    <p>Old Name:</p>
    <p><input type="text" value = "{{room.OldName}}" name = "Old Name"></p>
    <p><input type="submit" class="btn-xs" value="Save Old Name" name="Save Old Name" /></p>
</form>
<form action=""  method="POST" enctype="multipart/form-data" name="Type">
    {% csrf_token %}
    <p>Type:</p>
    <p><input type="text" value = "{{room.Type}}" name = "Type"></p>
    <p><input type="submit" class="btn-xs" value="Save Type" name="Save Type" /></p>
</form>
<form action=""  method="POST" enctype="multipart/form-data" name="Notes">
    {% csrf_token %}
    <p>Notes:</p>
    <p><input type="text" value = "{{room.Notes}}" name = "Notes" size = 100></p>
    <p><input type="submit" class="btn-xs" value="Save Notes" name="Save Notes" /></p>
</form>
<button class="btn-xs" id="delete_object">Delete</button>
<div id="myModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
    <form action=""  method="POST" enctype="multipart/form-data" name="Confirm">
    {% csrf_token %}
    <p>Are you sure you want to delete?
    <p>Enter Username and Password to confirm:</p>
    <p>Username: <input type="text" value = "Username" name = "Username"></p>
    <p>Password: <input type="password" value = "Password" name = "Password"></p>
    <p><input type="submit" class="btn-xs" value="Confirm" name="Confirm" /></p>
</form>
  </div>
</div>

<script>
var modal = document.getElementById('myModal');
var btn = document.getElementById("delete_object");
var span = document.getElementsByClassName("close")[0];
btn.onclick = function() {
    modal.style.display = "block";
}
span.onclick = function() {
    modal.style.display = "none";
}
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>
<p><a href="{% url 'energize_andover:room' room.id %}">Return To Room</a></p>
{% else %}
<h1> Room: {{room.Name}} </h1>
<p>School: <a href= "{% url 'energize_andover:school' school.id %}" >{{school.Name}}</a></p>

<li>Name: {{room.Name}}</li>
<li>Old Name: {{room.OldName}}</li>
<li>Type:<a href = "{% url 'energize_andover:dictionary' %}"> {{room.Type}}</a></li>


{% if not Panels.count == 0 %}
<form>
<p>Panels:</p>
    <ul>
{% for panel in Panels %}
    <li><a href="{% url 'energize_andover:panel' panel.id %}">{{panel.FQN}} ({{panel.Name}})</a></li>
{% endfor %}
</ul>
</form>
{% else %}
<p>Panel: No Panel data </p>
{% endif %}

{% if not Circuits.count == 0 %}
<form>
<p>Devices:</p>
<ul>
{% for circuit in Circuits %}
    <li><a href="{% url 'energize_andover:circuit' circuit.id %}">{{circuit.FQN}}  | {{circuit.Name}} | {{circuit.Function}}</a></li>
{% endfor %}
</ul>
</form>
{% else %}
<p>Devices: No Device data </p>
{% endif %}
<form action="{% url 'energize_andover:room_editing' room.id %}"  method="POST" enctype="multipart/form-data" name="Edit">
    {% csrf_token %}
    <p><input type="submit" class="btn-xs" value="Edit" name="Edit" /></p>
</form>
{% endif %}
{% endblock %}

energize_andover/templates/energize_andover/Search.html
{% extends "pages/richtextpage.html" %}

{% block main %}
<h1> Search for {{title}}: </h1>
<p>In {{schoo.Name}}</p>
{% if not panels|length == 0 %}
<p>Panels:</p>
{% for panel in panels %}
    <li> <a href="{% url 'energize_andover:panel' panel.id %}">{{panel.to_string}}</a></li>
{% endfor %}
{% endif %}

{% if not rooms|length == 0 %}
<p>Rooms:</p>
{% for room in rooms %}
    <li> <a href="{% url 'energize_andover:room' room.id %}">{{room.to_string}}</a></li>
{% endfor %}
{% endif %}

{% if not circuits|length == 0 %}
<p>Circuits: </p>
{% for circ in circuits %}
    <li><a href="{% url 'energize_andover:device' circ.id %}">{{circ.to_string}}</a></li>
{% endfor %}
{% endif %}

{% if not closets|length == 0 %}
<p>Closets:</p>
{% for closet in closets %}
    <li> <a href="{% url 'energize_andover:closet' closet.id %}">{{closet.to_string}}</a></li>
{% endfor %}
{% endif %}


<form action="{% url 'energize_andover:search' %}" method="GET" enctype="multipart/form-data">
  {% csrf_token %}
  <p>{{ form.entry.label }} {{ form.entry }}</p>
  <p>{{ form.panels.label }}: {{ form.panels }} (Acceptable Fields are: Name)</p>
  <p>{{ form.rooms.label }}: {{ form.rooms }} (Acceptable Fields are: Name, Old Name, Type)</p>
  <p>{{ form.circuits.label }}: {{ form.circuits }} (Acceptable Fields are: Device Name, Circuit Name)</p>
  <p>{{ form.closets.label }}: {{ form.closets }} (Acceptable Fields are: Name, Old Name)</p>
  <input type = "hidden" id = "school" name = "school" value="{{school}}">
  <input type="submit" class="btn btn-default" value="Search">
</form>

<li><a href="{% url 'energize_andover:school' schoo.pk%}">Return to {{schoo.Name}}</a></li>
{% endblock %}